apache:
 image: bharatak/bahmni-apache
 ports:
  - "49003:8080"
 volumes:
  - ~/dock/jss-config:/var/www/bahmni_config
  - ~/dock/openmrs-module-bahmniapps/ui/app:/var/www/bahmniapps
 links:
  - web
web:
 image: bharatak/bahmni-web
 ports:
  - "49001:8080"
 environment:
  - OPENMRS_RUNTIME_PROPERTIES_FILE=/root/.OpenMRS/openmrs-runtime.properties
 links:
  - mysql
 expose:
  - "8080"
 volumes:
  - ~/dock/openmrs-distro-bahmni/distro/target:/root/.OpenMRS/modules
mysql:
 image: bharatak/bahmni-mysql
 environment: 
  - MYSQL_ROOT_PASSWORD=password
 ports:
  - "49000:3306"
