web:
 image: bharatak/bahmni-web
 ports:
  - "49001:8080"
 volumes_from:
  - data
 environment:
  - OPENMRS_RUNTIME_PROPERTIES_FILE=/root/.OpenMRS/openmrs-runtime.properties
 links:
  - mysql
mysql:
 image: bharatak/bahmni-mysql
 environment: 
  - MYSQL_ROOT_PASSWORD=password
 ports:
  - "49000:3306"
 volumes_from:
  - data
data:
 image: bharatak/bahmni-data:latest