FROM mysql:5.6.23
MAINTAINER Bharat Akkinepalli <bharatak@thoughtworks.com>
ENV REFRESHED_AT 2015-02-15T20:40
ENV MYSQL_ROOT_PASSWORD password

VOLUME /var/lib/mysql

ADD mysql_backup.sql /root/mysql_backup.sql
